
local player = game.Players.LocalPlayer
local username = game.Workspace:FindFirstChild(player.Name)
local toolNames = {
    "AAC HONEY BADGER",
    "AK-74M",
    "AK-74U",
    "AK-BETA",
    "AK-PROTOTYPE",
    "AK-PROTOTYPE Project",
    "AK-PROTOTYPE(Custom)",
    "AK2077",
    "AK74-ALPHA",
    "AK74-COR",
    "AK74-Cerberus",
    "AK74-PMC",
    "AK74-SHF",
    "AK74-TFB",
    "AK74-Test",
    "AKS74U",
    "APC9-G2",
    "AR15-C",
    "AR15-LAS",
    "ARG-1",
    "ARG-2",
    "AS-VAL",
    "AS-VAL-Test",
    "AX-50",
    "Beretta 92A1",
    "Borchardt-Luger",
    "C3000-B",
    "C3000-R",
    "C480",
    "C900",
    "Colt 1911",
    "Colt_1911[Modification] ",
    "Cowboy John",
    "Deagle 44 Mod",
    "FN-SCAR-H",
    "Five-SeveN",
    "FiveSeven-S",
    "G-MP7",
    "G-MPX",
    "G-Vector",
    "Glock 26-S",
    "Glock13",
    "Glock14",
    "Glock21 Mod",
    "HK UMP",
    "KORD",
    "L-MP7",
    "L-Vector",
    "LS-MP7",
    "M249",
    "M249-PMC",
    "M4",
    "M4-C",
    "M4-LAS",
    "M4A1-ALP",
    "M4A1-Grenadier",
    "M4A1-Mod Cerberus",
    "M4A1-TFB",
    "M4A2-S",
    "M91-Containment",
    "MG-42",
    "MK18-PMC",
    "MK18-Reaper",
    "MK18-Test",
    "MK47-S Guard",
    "MK47-TFB",
    "MP-412 REX",
    "MP7-ART",
    "MP9",
    "NAGAN",
    "OP-SKS",
    "Origin-10",
    "Origin-12",
    "P-MP5SD",
    "P-MP5SD-2",
    "PKM",
    "PKM-JUG",
    "PKM-M",
    "PKM-URU",
    "PP-91 Kedr",
    "RPK-16 SHF",
    "SA-58 Cerberus",
    "SA58-TFB",
    "SAIGA-12",
    "SCAR-H Grenadier",
    "SCAR-H SFG",
    "SCAR-H SHF",
    "SCAR-L PMC",
    "SCAR-L SHF",
    "SCAR-L Test",
    "STI Glock 34",
    "SVD-S",
    "Shield[PP-Kedr]",
    "T-MP7",
    "T-MPX",
    "T-Vector",
    "Thompson SubmachineGun",
    "USP-S",
    "VSS-Vintorez"
}

while true do
    wait(0.1)
    for _, toolName in ipairs(toolNames) do
        local tool = player.Backpack:FindFirstChild(toolName) or username:FindFirstChild(toolName)
        
        if tool and tool:FindFirstChild("Memmory") and tool.Memmory:FindFirstChild("Ammo") then
            tool.Memmory.Ammo.Value = "999999999" 
        end
    end
end
